project_name: iskan
env:
  #- GO111MODULE=on
  #- GOPROXY=https://gocenter.io
before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/alcideio/iskan/pkg/version.Commit={{.Commit}} -X github.com/alcideio/iskan/pkg/version.Version={{.Version}}
    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: iskan
    # Path to main.go file or main package.
    # Default is `.`.
    main: main.go

    goos:
      - linux
      - darwin
      - windows
    goarch:
      #- 386
      - amd64
      #- arm
      #- arm64
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      post: /bin/bash hack/goreleaser-postbuild.sh

#signs:
#  - artifacts: checksum

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - id: default
    builds:
      - iskan
    name_template: '{{ .ProjectName }}_v{{ .Major }}.{{ .Minor }}.{{ .Patch }}_{{ .Os }}_{{ .Arch }}'
    format: binary

dockers:
  - image_templates:
      #- 'alcideio/skan:{{ .Tag }}'
      - 'alcide/iskan:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      - 'alcide/iskan:latest'
    dockerfile: Dockerfile
    binaries:
      - iskan
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=repository=https://github.com/alcideio/iskan"
      - "--label=homepage=https://github.com/alcideio/iskan"
      - "--label=maintainer=Alcide <iskan@alcide.io>"
    #      - "--label=org.opencontainers.image.source={{.GitURL}}"
    #      - "--label=com.github.actions.name={{.ProjectName}}"
    #      - "--label=com.github.actions.description=Deliver Go binaries as fast and easily as possible"
    #      - "--label=com.github.actions.icon=terminal"
    #      - "--label=com.github.actions.color=blue"
    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    skip_push: false
  - image_templates:
      - 'alcide/iskan:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-debug'
      - 'alcide/iskan:debug'
    dockerfile: debug.dockerfile
    binaries:
      - iskan
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=repository=https://github.com/alcideio/iskan"
      - "--label=homepage=https://github.com/alcideio/iskan"
      - "--label=maintainer=Alcide <iskan@alcide.io>"
    skip_push: false
  - image_templates:
      - 'alcide/iskan:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-localscan'
      - 'alcide/iskan:localscan'
    dockerfile: localscan.dockerfile
    binaries:
      - iskan
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=repository=https://github.com/alcideio/iskan"
      - "--label=homepage=https://github.com/alcideio/iskan"
      - "--label=maintainer=Alcide <iskan@alcide.io>"
    skip_push: false


release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: alcideio
    name: iskan

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  #disable: true

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base). If
  # another file with the same name exists, the latest one found will be used.
  # Defaults to empty.
  extra_files:
    - glob: ./artifacts/iskan-helm-chart.tar.gz


