image:
  iskan: alcide/iskan:localscan # or alcide/iskan:latest
  pullPolicy: IfNotPresent

#  string	   meaning
#  ------	   -------
#  @yearly	   Run once a year, "0 0 1 1 *".
#  @annually	 (same as @yearly)
#  @monthly	   Run once a month, "0	0 1 * *".
#  @weekly	   Run once a week, "0 0 * * 0".
#  @daily	     Run once a day, "0 0	* * *".
#  @midnight	 (same as @daily)
#  @hourly	   Run once an hour, "0	* * * *".
#  @every_minute   Run once a minute, "*/1 * * * *".
#  @every_second   Run once a second.
cronSchedule: "*/1 * * * *"

# The vulnerability credentials configurations
vulnProviderCredFile: config/providers.yaml

# The Report Policy configuration
reportPolicyFile: config/report-policy.yaml

runOptions:
  # -- Comma separated list of namespaces to scan or use '*' for all of them
  namespacesIncluded: "*"
  # -- Comma separated list of namespaces to exclude from the scan or use '-' to avoid exclusion
  namespacesExcluded: "kube-system"
  # -- The Vulnerability Provider API call rate limit (queries-per-sec)
  scanApiQPS: 30
  # -- The Vulnerability Provider API call burst limit
  scanApiBurst: 100
  # -- The report format - json or yaml
  reportFormat: "json"

export:
  # -- Export generated report to one or more export targets
  #  see: https://github.com/kruzio/exodus#supported-targets
  targets:
  - file:///path/to/dir
  - slack://mychannel?apikey=<mykey>[&file-type=json&title=MyClusterVulnReport
  - webhook://myserver?x-headers=X-myheader:myval&token-bearer=1234

