---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "alcide-iskan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "alcide-iskan.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  # Keep the last run 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1  
  # Concurrency is not required
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            alcide.io/iskan: "cronjob"
        spec:
          serviceAccountName: {{ template "alcide-iskan.fullname" . }}
          volumes:
            - name: outbox
              emptyDir: {}
            - name: workspace
              emptyDir: {}
            - name: report-config
              configMap:
                defaultMode: 420
                items:
                  - key: report-config.yaml
                    path: report-config.yaml
                name: report-config
            - name: vuln-providers-creds
              secret:
                defaultMode: 420
                items:
                  - key: providers.yaml
                    path: providers.yaml
                secretName: {{ template "alcide-iskan.fullname" . }}-creds

          containers:
          - name: exodus
            image: kruzio/exodus:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /outbox
                name: outbox
            args:
              - "sendfile"
              - "--watch"
              - "/outbox"
              - "--watch-forever"
              - "false"
              # Debugging
              #- "-v"
              #- "7"

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            env:
              - name: KRUZIO_EXODUS_SENDFILE_TARGETS
                valueFrom:
                  secretKeyRef:
                    name: {{ template "alcide-iskan.fullname" . }}-creds
                    key: targets
          - name: iskan
            image: {{ .Values.image.iskan }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:            
                - mountPath: /config
                  name: report-config
                - mountPath: /creds
                  name: vuln-providers-creds
                # Our Send Box
                - mountPath: /outbox
                  name: outbox
                - mountPath: /workspace
                  name: workspace
            args:
              - cluster
              - --namespace-include={{ .Values.runOptions.namespacesIncluded | quote }}
              - --namespace-exclude={{ .Values.runOptions.namespacesExcluded | quote }}
              - --format={{ .Values.runOptions.reportFormat }}
              - --scan-api-burst={{ .Values.runOptions.scanApiBurst}}
              - --scan-api-qps={{ .Values.runOptions.scanApiQPS}}
              - --outfile=/outbox/report
              - --api-config=/creds/providers.yaml
              - --report-config=/config/report-config.yaml
              #- -v=7 # Verbose level 10 will print secrets - DO NOT USE THAT
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 10001
              readOnlyRootFilesystem: false
          restartPolicy: OnFailure
