---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "alcide-iskan.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "alcide-iskan.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "alcide-iskan.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "alcide-iskan.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "alcide-iskan.fullname" . }}
    namespace: {{ .Release.Namespace }}
