---
name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Launch Cluster
        uses: helm/kind-action@v1.0.0
        with:
          version: v0.9.0
          cluster_name: iskan
          node_image: kindest/node:v1.19.1
          wait: 5m

      - name: E2E
        env:
          E2E_PIPELINE: ${{ secrets.E2E_PIPELINE }}
          E2E_GCR_PULLSECRET: ${{ secrets.E2E_GCR_PULLSECRET }}
          E2E_API_CONFIG: ${{ secrets.E2E_API_CONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AZURE_ACR_SP_USER: ${{ secrets.AZURE_ACR_SP_USER }}
          AZURE_ACR_SP_PASS: ${{ secrets.AZURE_ACR_SP_PASS }}
        run: |
          make e2e

      - name: Build & Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALCIDE_DOCKER_HUB_TOKEN: ${{ secrets.ALCIDE_DOCKER_HUB_TOKEN }}
        run: |
          docker login --username alcide --password=$ALCIDE_DOCKER_HUB_TOKEN
          make get-bins
          make gorelease